### ISSUE TITLE
[BUG]: Latest release breaks NGINX when using opentelemetry annotations

### ISSUE THREAD

**Issue by mifonpe** [DataDog/nginx-datadog#193]
### Module Version(s)

1.6.0

### Bug Report

Dear team,

We use the datadog agent and the nginx ingress controller in our cluster. To emit traces, we use the nginx-datadog module, loading it with the extraModules feature of the [NGINX ingress helm chart](https://github.com/kubernetes/ingress-nginx/blob/main/docs/deploy/index.md) (4.11.5), and pinning it to a specific version:

 ```
  extraModules:
    - name: nginx-datadog
      image:
        registry: docker.io
        image: datadog/ingress-nginx-injection
        tag: "v1.11.3"
        distroless: false

```
Last Tuesday 8th of April 2025, one of our nginx ingress controllers started crashing (all their pods) with the following error:

<img width="970" alt="Image" src="https://github.com/user-attachments/assets/24232ce0-a94b-4040-89f7-319e25e5eb46" />

We did not change anything in our setup so we searched in all our ingresses to find anything opentelemetry related, and we found an ingress with these 2 annotations:

```
nginx.ingress.kubernetes.io/opentelemetry-trust-incoming-span: "true"
nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
```

We deleted the annotations, uninstalled and reinstalled the NGINX helm released and the issue was solved.

The [documentation](https://github.com/DataDog/nginx-datadog/blob/master/doc/API.md#datadog_trust_incoming_span) of the module states that the directive is **datadog_trust_incoming_span** and yet seems that the new version of the library generates **datadog_trust_incoming_spans** (note the S) as in [this line](https://github.com/DataDog/nginx-datadog/pull/182/files#diff-21ef288732c1bc4d82dc26be3d9fa5e10c6226b4d255bd6127d8c3834fb10b92R157) of the [PR 182](https://github.com/DataDog/nginx-datadog/pull/182/files#), which was introduced in the last [release](https://github.com/DataDog/nginx-datadog/releases/tag/v1.6.0) (1.6.0).

I think that even though we pin the version of the Image containing the module (v1.11.3) [the image got rebuilt](https://hub.docker.com/layers/datadog/ingress-nginx-injection/v1.11.3/images/sha256-c34a1216ef88ab5002ea2f9ab869ae3cb3edf28b7b5c34b2f99ec0eff5735f04) on the release incorporating the latest changes to the module.

As you can see, the timeline matches exactly our issues, let me know if you need more information.

Thanks in advance.

### Reproduction Code

[](url)

### Error Logs

2025/04/08 10:15:33 [emerg] 73#73: unknown directive "datadog_trust_incoming_spans" in /tmp/nginx/nginx-cfg1898377719:8199

### Operating System

Bottlerocket OS 1.35.0 (aws-k8s-1.31)

**Comment by dmehala** [comment]
Hi @mifonpe 

Thank you for bringing this to our attention. You're absolutely right—this is a typo, and I take full responsibility for not catching it during testing.

I’ll work on resolving the issue and aim to release a patch as soon as possible. In the meantime, as a temporary workaround, I recommend pinning to the previous version using the following configuration:

```yaml
 extraModules:
   - name: nginx-datadog
     image:
       registry: docker.io
       image: datadog/ingress-nginx-injection
       tag: "v1.11.3-dd.v1.5.0"
       distroless: false
```
